apiVersion: v1
kind: ConfigMap
metadata:
  name: php-crud-config
  labels:
    app: php-crud
data:
  DB_HOST: "mysql"
  DB_NAME: "crud_app"
  DB_USER: "crud_user"
  PHP_OPCACHE_ENABLE: "1"
  PHP_MEMORY_LIMIT: "128M"
